### ISSUE TITLE
Atcoder broken url

### ISSUE THREAD

**Issue by bacali95** [nishanthvijayan/CoderCalendar-API#5]
Hello, I faced an issue when trying to open an AtCoder contest from the extension then it gives `chrome-extension://bageaffklfkikjigoclfgengklfnidll/contests/abc163` which means the URL is broken, so when I checked the API code it appear that is building the correct URL but the hosted API [api.codercalendar.io](api.codercalendar.io) is giving a wrong result, here is an [http://api.codercalendar.io/?platform=atcoder](example).

**Comment by nishanthvijayan** [comment]
Fixed. The issue was fixed in code a while ago but I guess I forgot to deploy.
